# Generated by Django 4.2.5 on 2023-10-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_profile_image_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='member',
        ),
    ]
