# Generated by Django 4.2.5 on 2023-10-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_user_attendance_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrecognizedFaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('decision', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='unrecognized_faces/')),
            ],
        ),
    ]
